### ISSUE TITLE
Module breaks on Rollup/Vite

### ISSUE THREAD

**Issue by jerryjappinen** [8base/sdk#378]
**Describe the bug**
When using the auth module on Nuxt 3, which runs on Rollup and Vite, the following error will come up:

```
Uncaught (in promise) TypeError: (0 , import_defineToJSON.default) is not a function
    at node_modules/graphql/language/parser.mjs (@8base_auth.js:17154:37)
    at __init (chunk-6DBBYCL5.js:16:56)
    at node_modules/graphql-prettier/lib/index.js (@8base_auth.js:17728:20)
    at __require2 (chunk-6DBBYCL5.js:19:50)
    at node_modules/@8base/utils/dist/queryGenerators/queryGenerators.js (@8base_auth.js:18088:46)
    at __require2 (chunk-6DBBYCL5.js:19:50)
    at node_modules/@8base/utils/dist/queryGenerators/index.js (@8base_auth.js:18370:18)
    at __require2 (chunk-6DBBYCL5.js:19:50)
    at node_modules/@8base/utils/dist/index.js (@8base_auth.js:18517:18)
    at __require2 (chunk-6DBBYCL5.js:19:50)
```

**To Reproduce**
Clone this repo, install dependencies and run `npm run dev`: https://github.com/jerryjappinen/8base-auth-parser

The dev server build will break, and app will not mount (empty screen).

**Expected behavior**
App should build without errors and print a list of authentication strategies imported from the module.

**Screenshots**
![image](https://user-images.githubusercontent.com/1101002/154799807-a0ff6003-7940-4af7-8667-8b49cf216570.png)

**Desktop**
macOS, Chrome

**Additional context**
More discussion here: https://community.8base.com/t/cant-get-8base-auth-to-work/861/5

**Comment by schmt5** [comment]
I got the same error. Is any workaround known?

**Comment by s1owjke** [comment]
@schmt5 can you try 3.x beta packages, also we moved all react packages under `@8base` namespace:
- `@8base/apollo-links@2.6.6` -> `@8base/apollo-links@3.0.0-beta.3`
- `@8base-react/auth@2.6.6` -> `@8base/react-auth@3.0.0-beta.3`
